# train

In [1]:
import yaml
import os

with open("./config.yaml", 'rb') as f:
    config = yaml.load(f)

<ipython-input-1-1499ab5789c7>:5: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)


In [2]:
OUTPUT_ROOT = config['IO_OPTION']['OUTPUT_ROOT']
os.makedirs(OUTPUT_ROOT, exist_ok=True)

## load library

In [3]:
# python default library
import os
import shutil
import datetime
import sys
import pickle

# general analysis tool-kit
import numpy as np
import pandas as pd
#from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

# pytorch
import torch
from torch import optim, nn
from torch.utils.tensorboard import SummaryWriter

#from torchsummary import summary

# etc
import yaml
yaml.warnings({'YAMLLoadWarning': False})

# original library
sys.path.append('/home/hiroki/research/dcase2021_task2/src/functions')
import common as com
import pytorch_modeler as modeler
from pytorch_model import ResNet38 as Model
#from pytorch_utils import filtered_load_model
#import models

import librosa
import IPython
import librosa.display

## load config and set logger

In [4]:
log_folder = config['IO_OPTION']['OUTPUT_ROOT']+'/{0}.log'.format(datetime.date.today())
logger = com.setup_logger(log_folder, '00_train.py')

## Setting

In [5]:
# Setting seed
modeler.set_seed(42)

In [6]:
############################################################################
# Setting I/O path
############################################################################
# input dirs
INPUT_ROOT = config['IO_OPTION']['INPUT_ROOT']
dev_dir = INPUT_ROOT + "/dev_data"
add_dev_dir = INPUT_ROOT + "/add_dev_data"
# machine type
machine_types = os.listdir(dev_dir)
# output dirs
OUTPUT_ROOT = config['IO_OPTION']['OUTPUT_ROOT']
MODEL_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/models'
TB_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/tb'
OUT_FEATURE_DIR = OUTPUT_ROOT + '/extraction_features'
#os.makedirs(OUTPUT_ROOT, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(TB_DIR, exist_ok=True)
os.makedirs(OUT_FEATURE_DIR, exist_ok=True)
# copy config
shutil.copy('./config.yaml', OUTPUT_ROOT)

'/media/hiroki/HDD1TB/research/dcase2021_task2/output/MahalanobisAD/config.yaml'

In [7]:
torch.cuda.is_available()

True

## make path list

- __train_paths__ ([dict]): Each Machine Type
    - __ToyCar__ ([dict]): Each dataset
        - train ([list]) : paths
        - valid_source ([list]) : paths
        - valid_target ([list]) :paths
    - __ToyTrain__ ([dict]): Each dataset
        - train ([list]) : paths
        - valid_source ([list]) : paths
        - valid_target ([list]) : paths
    - ...

In [8]:
dev_paths = {}

for machine_type in machine_types:
    # dev train
    dev_train_paths = [f"{dev_dir}/{machine_type}/train/" + file for file in os.listdir(f"{dev_dir}/{machine_type}/train")]
    dev_train_paths = sorted(dev_train_paths)
    
    # add_dev train
    #add_dev_paths = [f"{add_dev_dir}/{machine_type}/train/" + file for file in os.listdir(f"{add_dev_dir}/{machine_type}/train")]
    #add_dev_paths = sorted(add_dev_paths)
    
    # dev_source valid
    dev_source_paths = [f"{dev_dir}/{machine_type}/source_test/" + file for file in os.listdir(f"{dev_dir}/{machine_type}/source_test")]
    dev_source_paths = sorted(dev_source_paths)
    
    # dev_target valid
    dev_target_paths = [f"{dev_dir}/{machine_type}/target_test/" + file for file in os.listdir(f"{dev_dir}/{machine_type}/target_test")]
    dev_target_paths = sorted(dev_target_paths)
    
    # bundle
    dev_paths[machine_type] = {}
    dev_paths[machine_type]['train'] = dev_train_paths# + add_train_paths
    dev_paths[machine_type]['valid_source'] = dev_source_paths
    dev_paths[machine_type]['valid_target'] = dev_target_paths

## training

In [9]:
#############################################################################
# run
#############################################################################
def run(machine_type, dev_paths):
    com.tic()
    
    logger.info('TARGET MACHINE_TYPE: {0}'.format(machine_type))
    logger.info('MAKE DATA_LOADER')
    # dev_train_paths
    dataloaders_dict = modeler.make_dataloader(dev_paths, machine_type)
    # parameter setting
    logger.info('FEATURE EXTRACTION')
    net = Model(sample_rate=config['param']['sample_rate'],
                window_size=config['param']['window_size'],
                hop_size=config['param']['hop_size'],
                mel_bins=config['param']['mel_bins'],
                fmin=config['param']['fmin'],
                fmax=config['param']['fmax'])
    pretrained_dict = torch.load(config['IO_OPTION']['PREMODEL_ROOT'])
    net.load_state_dict(pretrained_dict, strict=False)
    output_dicts = modeler.extract_net(net, dataloaders_dict)
    out_path = f'{OUT_FEATURE_DIR}/{machine_type}_features.pkl'
    #pd.to_pickle(output_dicts, out_path)
    logger.info(f'SAVE SUCCESS : {out_path}')
    
    com.toc()

In [10]:
machine_types

['fan', 'gearbox', 'pump', 'slider', 'ToyCar', 'ToyTrain', 'valve']

In [11]:
for machine_type in machine_types:
    run(machine_type, dev_paths)

2021-03-18 16:28:24,131 - 00_train.py - INFO - TARGET MACHINE_TYPE: fan
2021-03-18 16:28:24,131 - 00_train.py - INFO - MAKE DATA_LOADER
2021-03-18 16:28:24,132 - 00_train.py - INFO - FEATURE EXTRACTION
  0%|          | 0/24 [00:00<?, ?it/s]

use: cuda:0
tensor([[0.0000, 0.0000, 1.4522,  ..., 0.0000, 2.4866, 0.4923],
        [0.0000, 0.0000, 1.5812,  ..., 0.0000, 2.7145, 0.5254],
        [0.0000, 0.0000, 1.7496,  ..., 0.0000, 2.9948, 0.5820],
        ...,
        [0.0000, 0.0000, 1.6398,  ..., 0.0000, 2.7994, 0.5495],
        [0.0000, 0.0000, 1.6262,  ..., 0.0000, 2.7924, 0.5402],
        [0.0000, 0.0000, 1.5785,  ..., 0.0000, 2.7091, 0.5245]],
       device='cuda:0')


  4%|▍         | 1/24 [00:01<00:45,  1.98s/it]

tensor([[0.0000, 0.0000, 1.4050,  ..., 0.0000, 2.4118, 0.4765],
        [0.0000, 0.0000, 1.6338,  ..., 0.0000, 2.7875, 0.5535],
        [0.0000, 0.0000, 1.5824,  ..., 0.0000, 2.7182, 0.5255],
        ...,
        [0.0000, 0.0000, 1.8350,  ..., 0.0000, 3.1416, 0.6108],
        [0.0000, 0.0000, 1.5771,  ..., 0.0000, 2.7080, 0.5241],
        [0.0000, 0.0000, 1.7372,  ..., 0.0000, 2.9824, 0.5776]],
       device='cuda:0')


  8%|▊         | 2/24 [00:03<00:37,  1.68s/it]

tensor([[0.0000, 0.0000, 1.5527,  ..., 0.0000, 2.6579, 0.5203],
        [0.0000, 0.0000, 1.6097,  ..., 0.0000, 2.7651, 0.5330],
        [0.0000, 0.0000, 1.6425,  ..., 0.0000, 2.8037, 0.5441],
        ...,
        [0.0000, 0.0000, 1.4656,  ..., 0.0000, 2.5143, 0.4940],
        [0.0000, 0.0000, 1.5954,  ..., 0.0000, 2.7399, 0.5297],
        [0.0000, 0.0000, 1.5912,  ..., 0.0000, 2.7312, 0.5277]],
       device='cuda:0')


 12%|█▎        | 3/24 [00:04<00:33,  1.62s/it]

tensor([[0.0000, 0.0000, 1.7219,  ..., 0.0000, 2.9519, 0.5730],
        [0.0000, 0.0000, 1.5793,  ..., 0.0000, 2.6900, 0.5351],
        [0.0000, 0.0000, 1.8209,  ..., 0.0000, 3.1012, 0.6148],
        ...,
        [0.0000, 0.0000, 1.8260,  ..., 0.0000, 3.1265, 0.6046],
        [0.0000, 0.0000, 1.5684,  ..., 0.0000, 2.6832, 0.5280],
        [0.0000, 0.0000, 1.5737,  ..., 0.0000, 2.6907, 0.5335]],
       device='cuda:0')


 17%|█▋        | 4/24 [00:06<00:31,  1.57s/it]

tensor([[0.0000, 0.0000, 1.7573,  ..., 0.0000, 3.0091, 0.5847],
        [0.0000, 0.0000, 1.5827,  ..., 0.0000, 2.7166, 0.5263],
        [0.0000, 0.0000, 1.4239,  ..., 0.0000, 2.4443, 0.4883],
        ...,
        [0.0000, 0.0000, 1.5502,  ..., 0.0000, 2.6524, 0.5227],
        [0.0000, 0.0000, 1.5981,  ..., 0.0000, 2.7317, 0.5390],
        [0.0000, 0.0000, 1.5885,  ..., 0.0000, 2.7267, 0.5280]],
       device='cuda:0')


 21%|██        | 5/24 [00:07<00:29,  1.53s/it]

tensor([[0.0000, 0.0000, 1.6408,  ..., 0.0000, 2.8128, 0.5463],
        [0.0000, 0.0000, 1.8438,  ..., 0.0000, 3.1570, 0.6110],
        [0.0000, 0.0000, 1.6175,  ..., 0.0000, 2.7790, 0.5360],
        ...,
        [0.0000, 0.0000, 1.8508,  ..., 0.0000, 3.1687, 0.6141],
        [0.0000, 0.0000, 1.4978,  ..., 0.0000, 2.5523, 0.5113],
        [0.0000, 0.0000, 1.5710,  ..., 0.0000, 2.6969, 0.5222]],
       device='cuda:0')


 25%|██▌       | 6/24 [00:09<00:27,  1.51s/it]

tensor([[0.0000e+00, 0.0000e+00, 1.5631e+00,  ..., 0.0000e+00, 2.6744e+00,
         5.2425e-01],
        [0.0000e+00, 0.0000e+00, 1.7143e+00,  ..., 0.0000e+00, 2.9333e+00,
         5.7157e-01],
        [0.0000e+00, 0.0000e+00, 1.8440e+00,  ..., 0.0000e+00, 3.1583e+00,
         6.1836e-01],
        ...,
        [8.7948e-06, 0.0000e+00, 1.5993e+00,  ..., 0.0000e+00, 2.7346e+00,
         5.3722e-01],
        [0.0000e+00, 0.0000e+00, 1.6051e+00,  ..., 0.0000e+00, 2.7424e+00,
         5.3977e-01],
        [0.0000e+00, 0.0000e+00, 1.5965e+00,  ..., 0.0000e+00, 2.7403e+00,
         5.3103e-01]], device='cuda:0')


 29%|██▉       | 7/24 [00:10<00:25,  1.51s/it]

tensor([[0.0000, 0.0000, 1.5148,  ..., 0.0000, 2.5989, 0.5063],
        [0.0000, 0.0000, 1.7463,  ..., 0.0000, 2.9905, 0.5806],
        [0.0000, 0.0000, 1.8877,  ..., 0.0000, 3.2322, 0.6287],
        ...,
        [0.0000, 0.0000, 1.4177,  ..., 0.0000, 2.4368, 0.4683],
        [0.0000, 0.0000, 1.1997,  ..., 0.0000, 2.0623, 0.4052],
        [0.0000, 0.0000, 1.3922,  ..., 0.0000, 2.3800, 0.4651]],
       device='cuda:0')


 33%|███▎      | 8/24 [00:12<00:24,  1.50s/it]

tensor([[0.0000e+00, 0.0000e+00, 1.4215e+00,  ..., 0.0000e+00, 2.4290e+00,
         4.7563e-01],
        [0.0000e+00, 0.0000e+00, 1.2142e+00,  ..., 0.0000e+00, 2.0861e+00,
         4.0894e-01],
        [0.0000e+00, 0.0000e+00, 1.4770e+00,  ..., 0.0000e+00, 2.5359e+00,
         4.8741e-01],
        ...,
        [0.0000e+00, 0.0000e+00, 1.3241e+00,  ..., 0.0000e+00, 2.2659e+00,
         4.4366e-01],
        [0.0000e+00, 0.0000e+00, 1.4319e+00,  ..., 0.0000e+00, 2.4625e+00,
         4.7132e-01],
        [6.4890e-07, 0.0000e+00, 1.3563e+00,  ..., 0.0000e+00, 2.3277e+00,
         4.4785e-01]], device='cuda:0')


 38%|███▊      | 9/24 [00:13<00:22,  1.52s/it]

tensor([[0.0000e+00, 0.0000e+00, 1.4555e+00,  ..., 0.0000e+00, 2.4872e+00,
         4.8859e-01],
        [0.0000e+00, 0.0000e+00, 1.3813e+00,  ..., 0.0000e+00, 2.3634e+00,
         4.5879e-01],
        [5.1047e-06, 0.0000e+00, 1.4862e+00,  ..., 0.0000e+00, 2.5493e+00,
         4.9151e-01],
        ...,
        [0.0000e+00, 0.0000e+00, 1.4168e+00,  ..., 0.0000e+00, 2.4373e+00,
         4.6638e-01],
        [4.3294e-07, 0.0000e+00, 1.3750e+00,  ..., 0.0000e+00, 2.3601e+00,
         4.5399e-01],
        [0.0000e+00, 0.0000e+00, 1.3500e+00,  ..., 0.0000e+00, 2.3252e+00,
         4.4785e-01]], device='cuda:0')


 42%|████▏     | 10/24 [00:15<00:21,  1.51s/it]

tensor([[0.0000e+00, 0.0000e+00, 1.2463e+00,  ..., 0.0000e+00, 2.1369e+00,
         4.1794e-01],
        [0.0000e+00, 0.0000e+00, 1.2135e+00,  ..., 0.0000e+00, 2.0663e+00,
         4.2070e-01],
        [0.0000e+00, 0.0000e+00, 1.4773e+00,  ..., 0.0000e+00, 2.5353e+00,
         4.8755e-01],
        ...,
        [5.0068e-06, 0.0000e+00, 1.6433e+00,  ..., 0.0000e+00, 2.8182e+00,
         5.4237e-01],
        [0.0000e+00, 0.0000e+00, 1.2138e+00,  ..., 0.0000e+00, 2.0895e+00,
         4.0895e-01],
        [0.0000e+00, 0.0000e+00, 1.4116e+00,  ..., 0.0000e+00, 2.4114e+00,
         4.7142e-01]], device='cuda:0')


 46%|████▌     | 11/24 [00:16<00:19,  1.51s/it]

tensor([[0.0000, 0.0000, 1.3980,  ..., 0.0000, 2.4029, 0.4608],
        [0.0000, 0.0000, 1.4557,  ..., 0.0000, 2.4959, 0.4822],
        [0.0000, 0.0000, 1.1983,  ..., 0.0000, 2.0499, 0.4144],
        ...,
        [0.0000, 0.0000, 1.4043,  ..., 0.0000, 2.3937, 0.4672],
        [0.0000, 0.0000, 1.7462,  ..., 0.0000, 2.9937, 0.5773],
        [0.0000, 0.0000, 1.4248,  ..., 0.0000, 2.4510, 0.4702]],
       device='cuda:0')


 50%|█████     | 12/24 [00:19<00:21,  1.82s/it]

tensor([[0.0000, 0.0000, 1.4170,  ..., 0.0000, 2.4374, 0.4673],
        [0.0000, 0.0000, 1.4750,  ..., 0.0000, 2.5309, 0.4867],
        [0.0000, 0.0000, 1.4426,  ..., 0.0000, 2.4807, 0.4755],
        ...,
        [0.0000, 0.0000, 1.4221,  ..., 0.0000, 2.4452, 0.4682],
        [0.0000, 0.0000, 1.4040,  ..., 0.0000, 2.4135, 0.4637],
        [0.0000, 0.0000, 1.3907,  ..., 0.0000, 2.3770, 0.4671]],
       device='cuda:0')


 54%|█████▍    | 13/24 [00:21<00:22,  2.02s/it]

tensor([[0.0000, 0.0000, 1.4173,  ..., 0.0000, 2.4390, 0.4668],
        [0.0000, 0.0000, 1.5887,  ..., 0.0000, 2.7239, 0.5234],
        [0.0000, 0.0000, 1.4050,  ..., 0.0000, 2.4044, 0.4655],
        ...,
        [0.0000, 0.0000, 1.4296,  ..., 0.0000, 2.4437, 0.4775],
        [0.0000, 0.0000, 1.2061,  ..., 0.0000, 2.0630, 0.4166],
        [0.0000, 0.0000, 1.4491,  ..., 0.0000, 2.4758, 0.4827]],
       device='cuda:0')


 58%|█████▊    | 14/24 [00:24<00:21,  2.14s/it]

tensor([[0.0000, 0.0000, 1.6516,  ..., 0.0000, 2.8326, 0.5426],
        [0.0000, 0.0000, 1.4155,  ..., 0.0000, 2.4163, 0.4771],
        [0.0000, 0.0000, 1.4134,  ..., 0.0000, 2.4294, 0.4666],
        ...,
        [0.0000, 0.0000, 1.6443,  ..., 0.0000, 2.8184, 0.5405],
        [0.0000, 0.0000, 1.3527,  ..., 0.0000, 2.3092, 0.4535],
        [0.0000, 0.0000, 1.4343,  ..., 0.0000, 2.4507, 0.4790]],
       device='cuda:0')


 62%|██████▎   | 15/24 [00:26<00:19,  2.22s/it]

tensor([[0.0000, 0.0000, 1.5796,  ..., 0.0000, 2.7026, 0.5198],
        [0.0000, 0.0000, 1.6352,  ..., 0.0000, 2.8039, 0.5372],
        [0.0000, 0.0000, 1.3588,  ..., 0.0000, 2.3205, 0.4606],
        ...,
        [0.0000, 0.0000, 1.7056,  ..., 0.0000, 2.9191, 0.5683],
        [0.0000, 0.0000, 1.5506,  ..., 0.0000, 2.6491, 0.5219],
        [0.0000, 0.0000, 1.3989,  ..., 0.0000, 2.4060, 0.4708]],
       device='cuda:0')


 67%|██████▋   | 16/24 [00:29<00:18,  2.30s/it]

tensor([[0.0000, 0.0000, 1.5326,  ..., 0.0000, 2.6288, 0.5120],
        [0.0000, 0.0000, 1.5748,  ..., 0.0000, 2.6923, 0.5343],
        [0.0000, 0.0000, 1.5429,  ..., 0.0000, 2.6462, 0.5149],
        ...,
        [0.0000, 0.0000, 1.6018,  ..., 0.0000, 2.7320, 0.5383],
        [0.0000, 0.0000, 1.5607,  ..., 0.0000, 2.6678, 0.5241],
        [0.0000, 0.0000, 1.5328,  ..., 0.0000, 2.6230, 0.5171]],
       device='cuda:0')


 71%|███████   | 17/24 [00:31<00:16,  2.31s/it]

tensor([[0.0000, 0.0000, 1.4118,  ..., 0.0000, 2.4263, 0.4757],
        [0.0000, 0.0000, 1.5555,  ..., 0.0000, 2.6680, 0.5180],
        [0.0000, 0.0000, 1.5404,  ..., 0.0000, 2.6417, 0.5140],
        ...,
        [0.0000, 0.0000, 1.5789,  ..., 0.0000, 2.7075, 0.5306],
        [0.0000, 0.0000, 1.7268,  ..., 0.0000, 2.9553, 0.5749],
        [0.0000, 0.0000, 1.4224,  ..., 0.0000, 2.4330, 0.4816]],
       device='cuda:0')


 75%|███████▌  | 18/24 [00:33<00:13,  2.26s/it]

tensor([[0.0000, 0.0000, 1.5321,  ..., 0.0000, 2.6201, 0.5139],
        [0.0000, 0.0000, 1.5484,  ..., 0.0000, 2.6554, 0.5161],
        [0.0000, 0.0000, 1.4126,  ..., 0.0000, 2.4241, 0.4777],
        ...,
        [0.0000, 0.0000, 1.6015,  ..., 0.0000, 2.7358, 0.5387],
        [0.0000, 0.0000, 1.5425,  ..., 0.0000, 2.6401, 0.5167],
        [0.0000, 0.0000, 1.4679,  ..., 0.0000, 2.5048, 0.5020]],
       device='cuda:0')


 79%|███████▉  | 19/24 [00:35<00:11,  2.25s/it]

tensor([[0.0000, 0.0000, 1.5545,  ..., 0.0000, 2.6670, 0.5171],
        [0.0000, 0.0000, 1.5712,  ..., 0.0000, 2.6865, 0.5223],
        [0.0000, 0.0000, 1.4750,  ..., 0.0000, 2.5323, 0.4930],
        ...,
        [0.0000, 0.0000, 1.5382,  ..., 0.0000, 2.6264, 0.5163],
        [0.0000, 0.0000, 1.5303,  ..., 0.0000, 2.6165, 0.5175],
        [0.0000, 0.0000, 1.5412,  ..., 0.0000, 2.6442, 0.5135]],
       device='cuda:0')


 83%|████████▎ | 20/24 [00:38<00:08,  2.24s/it]

tensor([[0.0000, 0.0000, 1.5196,  ..., 0.0000, 2.6050, 0.5075],
        [0.0000, 0.0000, 1.4633,  ..., 0.0000, 2.4909, 0.4996],
        [0.0000, 0.0000, 1.6214,  ..., 0.0000, 2.7792, 0.5412],
        ...,
        [0.0000, 0.0000, 1.5790,  ..., 0.0000, 2.7053, 0.5275],
        [0.0000, 0.0000, 1.5364,  ..., 0.0000, 2.6368, 0.5113],
        [0.0000, 0.0000, 1.5029,  ..., 0.0000, 2.5727, 0.5033]],
       device='cuda:0')


 88%|████████▊ | 21/24 [00:40<00:06,  2.23s/it]

tensor([[0.0000, 0.0000, 1.3542,  ..., 0.0000, 2.3138, 0.4706],
        [0.0000, 0.0000, 1.3600,  ..., 0.0000, 2.3322, 0.4650],
        [0.0000, 0.0000, 1.5435,  ..., 0.0000, 2.6483, 0.5145],
        ...,
        [0.0000, 0.0000, 1.4621,  ..., 0.0000, 2.4914, 0.4968],
        [0.0000, 0.0000, 1.5580,  ..., 0.0000, 2.6735, 0.5185],
        [0.0000, 0.0000, 1.5697,  ..., 0.0000, 2.6913, 0.5233]],
       device='cuda:0')


 92%|█████████▏| 22/24 [00:42<00:04,  2.21s/it]

tensor([[0.0000, 0.0000, 1.6067,  ..., 0.0000, 2.7518, 0.5363],
        [0.0000, 0.0000, 1.4367,  ..., 0.0000, 2.4644, 0.4839],
        [0.0000, 0.0000, 1.5460,  ..., 0.0000, 2.6515, 0.5160],
        ...,
        [0.0000, 0.0000, 1.5437,  ..., 0.0000, 2.6475, 0.5146],
        [0.0000, 0.0000, 1.5531,  ..., 0.0000, 2.6559, 0.5185],
        [0.0000, 0.0000, 1.3790,  ..., 0.0000, 2.3597, 0.4759]],
       device='cuda:0')


 96%|█████████▌| 23/24 [00:44<00:02,  2.21s/it]

tensor([[0.0000, 0.0000, 1.5796,  ..., 0.0000, 2.6992, 0.5310],
        [0.0000, 0.0000, 1.5298,  ..., 0.0000, 2.6162, 0.5181],
        [0.0000, 0.0000, 1.5223,  ..., 0.0000, 2.6118, 0.5080],
        ...,
        [0.0000, 0.0000, 1.5513,  ..., 0.0000, 2.6588, 0.5200],
        [0.0000, 0.0000, 1.4758,  ..., 0.0000, 2.5295, 0.4974],
        [0.0000, 0.0000, 1.4913,  ..., 0.0000, 2.5532, 0.5011]],
       device='cuda:0')


  0%|          | 0/5 [00:00<?, ?it/s]


file_broken or not exists!! : /media/hiroki/HDD1TB/research/dcase2021_task2/datasets/dev_data/fan/source_test/section_00_source_test_anomaly_0006.wav


TypeError: 'NoneType' object is not subscriptable

In [ ]:
machine_type = 'pump'
input_path = f'{OUT_FEATURE_DIR}/{machine_type}_features.pkl'
ext_data = pd.read_pickle(input_path)

In [ ]:
plt.figure(figsize=(10,10))
plt.imshow(ext_data['train']['features'], cmap='jet')
plt.colorbar()

In [ ]:
plt.figure(figsize=(10,10))
plt.imshow(ext_data['valid_source']['features'], cmap='jet')
plt.colorbar()

In [ ]:
plt.figure(figsize=(10,10))
plt.imshow(ext_data['train']['features'], cmap='jet')
plt.colorbar()

history = run('ToyCar')
with open('{}/{}_history.pkl'.format(PKL_DIR, machine_type), 'wb') as file:
    pickle.dump(history , file)

In [ ]:
print(M_means.shape)
plt.imshow(M_means, aspect='auto', cmap='jet')
plt.title(phase)
plt.colorbar()
plt.show()